### ISSUE TITLE
unable to resolve urls from csv

### ISSUE THREAD

**Issue by weiaiwayne** [QUT-Digital-Observatory/coordination-network-toolkit#42]
I have a column of URLs prepared according to the sample data ([see the output from pandas](https://www.dropbox.com/s/f1to4gz26f579x1/Screen%20Shot%202022-03-15%20at%205.08.42%20PM.png?dl=0)) but could not resolve any URL there. I checked the saved coord_1.db, looks like the 'message_url' table is empty.

**Comment by SamHames** [comment]
Ohhh, that looks like an oversight in the design there - the preprocess_data function expects the space separated list of URLs that is needed for CSV format, not the more logical list of URLs like you'd expect. I'll push a new version with a fix.

**Comment by SamHames** [comment]
Have a try against version 1.5.1 - assuming I haven't broken anything that should fix the issue.

**Comment by SamHames** [comment]
Going to close this one now - feel free to reopen if you're running into the same issue still.
