### ISSUE TITLE
 NetworkXNotImplemented: not implemented for directed type

### ISSUE THREAD

**Issue by Monika-cnb** [QUT-Digital-Observatory/coordination-network-toolkit#53]
Hi,

I get this error while trying to plot the graph. 
I'm able to plot the graph in a different way but I'm not sure why the below code is not working for me.
" for g in nx.connected_components(similarity_graph):
    print(g)" 

What can I do to resolve this error?

Thanks

**Comment by deimosnz** [comment]
Hi,

Please send through the error text you get. That would be a great help. 

Thanks
Rob

**Comment by Monika-cnb** [comment]
Hi Rob,

This is the error I'm getting. Everything else apart from this is working fine.
![image](https://user-images.githubusercontent.com/113090443/211431710-8083e572-3497-4cd8-bce6-2aad8b351962.png)

Thanks

**Comment by deimosnz** [comment]
Thanks,

"connected_components" is not implemented for directed graphs as per the docs for networkx - https://networkx.org/documentation/stable/reference/algorithms/generated/networkx.algorithms.components.connected_components.html#networkx.algorithms.components.connected_components

In short, directed graphs do not support connected components in the same way as undirected graphs.

The networkx functions "strongly_connected_components" or "weakly_connected_components" should be passed for directed graphs (see the docs linked in the page I have linked for you above)

It may be possible to use other community detection algorithms to achieve similar partitioning of your graph.

I hope this helps and come back to me if it doesn't.

Thanks

Rob

**Comment by Monika-cnb** [comment]
Thanks for linking the docs, Rob.

I'll take a look at the docs and try with different networkx functions.

Thanks for your help.

Best, Monika
